// <auto-generated />
using System;
using BlazorApp1.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230304181545_UserDetailUserNameGone")]
    partial class UserDetailUserNameGone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "battery-full",
                            Name = "Standard cars",
                            Url = "standard"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "camera-slr",
                            Name = "Cars film",
                            Url = "cars"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "aperture",
                            Name = "Cars from movies",
                            Url = "movies"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Edition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Editions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Buy now"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Lotus Elise is available with a 1.8-litre, four-cylinder engine in two states of tune. The Sport 220 offers 217bhp, while the Cup 250 makes a stronger case for itself with 243bhp. Both have identical torque figures at 184lb ft, but the Cup 250 develops its pulling power lower down the rev range. Acceleration from 0-62mph takes 4.6 seconds and 4.3 seconds respectively, with the pair moving on to ample top speeds of 145mph and 150mph via the six-speed manual transmission. The Elise is also one of the few cars on the road with no power steering, which results in a fantastic accuracy and amount of feel through the wheel.",
                            Image = "https://www.topgear.com/sites/default/files/cars-car/carousel/2019/07/751a3478_0.jpg?w=892&h=502",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Lotus Elise"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightning McQueen is a 2006 Custom-Built Piston Cup Racing stock car, with a top speed of 198mph, and accelerattion of 0-60 in 4 seconds. Lightning's body is built from 24-gauge Cold-rolled Sheet Steel, and chassis has a high strength tubular frame.",
                            Image = "https://images.squarespace-cdn.com/content/v1/5ae237043917eef6a6aeebce/1524780584779-3K5X1Q384A7QF4PA2UU4/IMG_0959.JPG?format=1000w",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Lightning McQueen"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            DateCreated = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Porche did good",
                            Image = "https://media.autoexpress.co.uk/image/private/s--8Hv5ZbZt--/v1661262351/evo/2022/08/Porsche%20911%20Sally%20Carrera%20Special%20Edition%20high%20res-2.jpg",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "Sally Car"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            DateCreated = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Helped Woody get onto the moving van",
                            Image = "https://cdn.shopify.com/s/files/1/2278/2841/products/HOW-DIES-RETO-ASST-fyp68-2_1024x1024@2x.jpg?v=1592146087",
                            IsDeleted = false,
                            IsPublic = false,
                            Title = "RC Car"
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.ProductVariant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("EditionId")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "EditionId");

                    b.HasIndex("EditionId");

                    b.ToTable("ProductVariant");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            EditionId = 2,
                            OriginalPrice = 99000m,
                            Price = 97990m,
                            Quantity = 40
                        },
                        new
                        {
                            ProductId = 1,
                            EditionId = 3,
                            OriginalPrice = 129990m,
                            Price = 109990m,
                            Quantity = 45
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 2,
                            OriginalPrice = 81700m,
                            Price = 81700m,
                            Quantity = 150
                        },
                        new
                        {
                            ProductId = 2,
                            EditionId = 3,
                            OriginalPrice = 95000m,
                            Price = 87110m,
                            Quantity = 155
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 2,
                            OriginalPrice = 3100000m,
                            Price = 3100000m,
                            Quantity = 90
                        },
                        new
                        {
                            ProductId = 3,
                            EditionId = 3,
                            OriginalPrice = 3600000m,
                            Price = 3600000m,
                            Quantity = 95
                        },
                        new
                        {
                            ProductId = 4,
                            EditionId = 2,
                            OriginalPrice = 30.99m,
                            Price = 27.99m,
                            Quantity = 200
                        },
                        new
                        {
                            ProductId = 4,
                            EditionId = 3,
                            OriginalPrice = 40.99m,
                            Price = 34.99m,
                            Quantity = 205
                        });
                });

            modelBuilder.Entity("BlazorApp1.Shared.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Product", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlazorApp1.Shared.ProductVariant", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Edition", "Edition")
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Shared.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
